// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/mock_definitions.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:frontend/proto/event_bus.pb.dart' as _i5;
import 'package:frontend/proto/event_bus.pbgrpc.dart' as _i4;
import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:protobuf/well_known_types/google/protobuf/empty.pb.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseStream_0<R> extends _i1.SmartFake
    implements _i2.ResponseStream<R> {
  _FakeResponseStream_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseFuture_1<R> extends _i1.SmartFake
    implements _i2.ResponseFuture<R> {
  _FakeResponseFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientCall_2<Q1, R1> extends _i1.SmartFake
    implements _i3.ClientCall<Q1, R1> {
  _FakeClientCall_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventBusServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventBusServiceClient extends _i1.Mock
    implements _i4.EventBusServiceClient {
  @override
  _i2.ResponseStream<_i5.Event> eventBus(
    _i5.EventBusRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#eventBus, [request], {#options: options}),
            returnValue: _FakeResponseStream_0<_i5.Event>(
              this,
              Invocation.method(#eventBus, [request], {#options: options}),
            ),
            returnValueForMissingStub: _FakeResponseStream_0<_i5.Event>(
              this,
              Invocation.method(#eventBus, [request], {#options: options}),
            ),
          )
          as _i2.ResponseStream<_i5.Event>);

  @override
  _i2.ResponseFuture<_i6.Empty> subscribe(
    _i5.SubscribeRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [request], {#options: options}),
            returnValue: _FakeResponseFuture_1<_i6.Empty>(
              this,
              Invocation.method(#subscribe, [request], {#options: options}),
            ),
            returnValueForMissingStub: _FakeResponseFuture_1<_i6.Empty>(
              this,
              Invocation.method(#subscribe, [request], {#options: options}),
            ),
          )
          as _i2.ResponseFuture<_i6.Empty>);

  @override
  _i2.ResponseFuture<_i6.Empty> unsubscribe(
    _i5.UnsubscribeRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [request], {#options: options}),
            returnValue: _FakeResponseFuture_1<_i6.Empty>(
              this,
              Invocation.method(#unsubscribe, [request], {#options: options}),
            ),
            returnValueForMissingStub: _FakeResponseFuture_1<_i6.Empty>(
              this,
              Invocation.method(#unsubscribe, [request], {#options: options}),
            ),
          )
          as _i2.ResponseFuture<_i6.Empty>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i7.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_2<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_2<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_1<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_1<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i7.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_0<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_0<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}
