// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:frontend/firebase/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuiKmtU3jg6oVsuela9Fq7oTUF5xwXLQM',
    appId: '1:467071326079:web:d694cf5f9a72ced51bec4a',
    messagingSenderId: '467071326079',
    projectId: 'social-example-dev',
    authDomain: 'social-example-dev.firebaseapp.com',
    storageBucket: 'social-example-dev.firebasestorage.app',
    measurementId: 'G-SKRXDT5V8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqMIdByrSFEugvvhHD9tEY5DPekgYWLTE',
    appId: '1:467071326079:android:3f5cfd4de9bf554b1bec4a',
    messagingSenderId: '467071326079',
    projectId: 'social-example-dev',
    storageBucket: 'social-example-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj_sT0So91i1DAHLuE6l6BC6BNBJQyiEM',
    appId: '1:467071326079:ios:91ac4a855002f6561bec4a',
    messagingSenderId: '467071326079',
    projectId: 'social-example-dev',
    storageBucket: 'social-example-dev.firebasestorage.app',
    iosBundleId: 'example.social',
  );
}
