#!/usr/bin/env bash
# Local single-node Rama cluster (path A): devZookeeper + conductor + supervisor.
# Docs: https://redplanetlabs.com/docs/~/operating-rama.html (Running single-node cluster)
#
# RAMA_HOME = <repository-root>/cluster/ (created on first start; entire directory is gitignored).
# This script lives in scripts/. `start` auto-downloads Rama 1.6.0 from S3 when ./rama is missing,
# then launches daemons. Running `start` again stops tracked daemons first (same as `stop`)
# then starts fresh — no separate `restart` command.
#
# Usage (from any cwd):
#   /path/to/repo/scripts/rama_local.sh start|stop|status
#
# Under RAMA_HOME (cluster/):
#   .local-one-node-cluster/logs/  — stdout/stderr from nohup when launching each daemon
#   logs/                           — Rama Log4j output (from release log4j2.properties; CWD is RAMA_HOME)
#   local-rama-data/                — Conductor/Supervisor local.dir (see generated rama.yaml)
#   local-zk/                       — devZookeeper persistence (created by Rama; not production ZK)
#
# Not production-safe: devZookeeper is experimental per Rama docs.
set -euo pipefail

# --- hardcoded download + cluster tuning (edit here only; no env overrides) ---
readonly rama_release_zip_url="https://redplanetlabs.s3.us-west-2.amazonaws.com/rama/rama-1.6.0.zip"
# Top-level directory name inside the zip (matches archive name); verify if Red Planet changes layout.
readonly rama_release_root_dir="rama-1.6.0"
readonly zk_host="127.0.0.1"
readonly conductor_host="127.0.0.1"
readonly supervisor_host="127.0.0.1"
readonly zk_port="2000"
readonly zk_ready_seconds="3"
readonly conductor_ready_seconds="3"
readonly cluster_ui_port="8888"
# --- end hardcoded config ---

readonly _scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly _repo_root="$(cd "$_scripts_dir/.." && pwd)"
readonly RAMA_HOME="$_repo_root/cluster"
readonly state_dir_name=".local-one-node-cluster"
readonly extract_staging_dir="$RAMA_HOME/.rama-extract-staging"

usage() {
  echo "usage: $(basename "$0") start|stop|status" >&2
  echo "  RAMA_HOME: $RAMA_HOME (gitignored)" >&2
  exit 1
}

require_rama_home() {
  if [[ ! -x "$RAMA_HOME/rama" ]]; then
    echo "error: not executable: $RAMA_HOME/rama (prepare/download failed?)" >&2
    exit 1
  fi
}

download() {
  command -v curl >/dev/null || { echo "error: curl not on PATH (needed for first start)" >&2; exit 1; }
  command -v unzip >/dev/null || { echo "error: unzip not on PATH (needed for first start)" >&2; exit 1; }

  local archive_name
  archive_name="${rama_release_zip_url##*/}"
  local zip_path="$RAMA_HOME/$archive_name"

  rm -rf "$extract_staging_dir"
  mkdir -p "$extract_staging_dir"
  curl -fL "$rama_release_zip_url" -o "$zip_path"
  unzip -q "$zip_path" -d "$extract_staging_dir"

  if [[ -d "$extract_staging_dir/$rama_release_root_dir" ]]; then
    shopt -s dotglob nullglob
    for path in "$extract_staging_dir/$rama_release_root_dir"/*; do
      mv "$path" "$RAMA_HOME/"
    done
    shopt -u dotglob nullglob
  else
    shopt -s dotglob nullglob
    for path in "$extract_staging_dir"/*; do
      mv "$path" "$RAMA_HOME/"
    done
    shopt -u dotglob nullglob
  fi

  rm -rf "$extract_staging_dir" "$zip_path"
  echo "fetched Rama release into $RAMA_HOME"
}

prepare() {
  mkdir -p "$RAMA_HOME"
  command -v java >/dev/null || { echo "error: java not on PATH" >&2; exit 1; }
  command -v python3 >/dev/null || { echo "error: python3 not on PATH" >&2; exit 1; }
  if [[ ! -x "$RAMA_HOME/rama" ]]; then
    download
  fi
  require_rama_home
}

state_dir() {
  echo "$RAMA_HOME/$state_dir_name"
}

ensure_state_dir() {
  mkdir -p "$(state_dir)/logs" "$(state_dir)/pids"
}

write_rama_yaml() {
  local local_dir="$RAMA_HOME/local-rama-data"
  mkdir -p "$local_dir"
  cat >"$RAMA_HOME/rama.yaml" <<EOF
# Generated by $(basename "$0") — single-node local cluster (path A).
zookeeper.servers:
  - "$zk_host"
zookeeper.port: $zk_port
conductor.host: "$conductor_host"
supervisor.host: "$supervisor_host"
local.dir: "$local_dir"
EOF
}

start_bg() {
  local name=$1
  shift
  local log
  log="$(state_dir)/logs/${name}.log"
  nohup "$@" >>"$log" 2>&1 &
  echo $! >"$(state_dir)/pids/${name}.pid"
  echo "started $name pid=$(cat "$(state_dir)/pids/${name}.pid") log=$log"
}

start() {
  prepare
  ensure_state_dir
  stop_daemons

  if [[ ! -f "$RAMA_HOME/rama.yaml.user-backup" ]] && [[ -f "$RAMA_HOME/rama.yaml" ]]; then
    cp "$RAMA_HOME/rama.yaml" "$RAMA_HOME/rama.yaml.user-backup"
    echo "backed up prior rama.yaml -> rama.yaml.user-backup"
  fi
  write_rama_yaml

  cd "$RAMA_HOME"
  start_bg devZookeeper ./rama devZookeeper
  sleep "$zk_ready_seconds"
  start_bg conductor ./rama conductor
  sleep "$conductor_ready_seconds"
  start_bg supervisor ./rama supervisor

  echo "Cluster UI (default): http://${conductor_host}:${cluster_ui_port}"
  echo "Logs: nohup $(state_dir)/logs/  |  Log4j $RAMA_HOME/logs/"
}

stop_one() {
  local name=$1
  local f
  f="$(state_dir)/pids/${name}.pid"
  if [[ ! -f "$f" ]]; then
    echo "no pid file for $name"
    return 0
  fi
  local pid
  pid=$(cat "$f")
  if kill -0 "$pid" 2>/dev/null; then
    kill -TERM "$pid" 2>/dev/null || true
    for _ in $(seq 1 30); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.2
    done
    if kill -0 "$pid" 2>/dev/null; then
      kill -KILL "$pid" 2>/dev/null || true
    fi
    echo "stopped $name (pid $pid)"
  else
    echo "$name pid $pid not running"
  fi
  rm -f "$f"
}

stop_daemons() {
  stop_one supervisor
  stop_one conductor
  stop_one devZookeeper
}

stop() {
  stop_daemons
}

status() {
  local name pid f
  for name in devZookeeper conductor supervisor; do
    f="$(state_dir)/pids/${name}.pid"
    if [[ -f "$f" ]]; then
      pid=$(cat "$f")
      if kill -0 "$pid" 2>/dev/null; then
        echo "$name: running pid=$pid"
      else
        echo "$name: stale pid=$pid"
      fi
    else
      echo "$name: not started (no pid file)"
    fi
  done
  echo "Cluster UI (default): http://${conductor_host}:${cluster_ui_port}"
  echo "nohup wrapper logs: $(state_dir)/logs/"
  echo "Rama Log4j logs:     $RAMA_HOME/logs/"
  echo "local.dir data:     $RAMA_HOME/local-rama-data/"
  if [[ -d "$RAMA_HOME/local-zk" ]]; then
    echo "dev ZK data:        $RAMA_HOME/local-zk/"
  fi
  if [[ ! -x "$RAMA_HOME/rama" ]]; then
    echo "note: $RAMA_HOME/rama missing — run start to fetch and launch" >&2
  fi
}

main() {
  [[ $# -eq 1 ]] || usage
  case "$1" in
    start) start ;;
    stop) stop ;;
    status) status ;;
    *) usage ;;
  esac
}

main "$@"
